# numpy vs list 

In [4]:
list1=[1,4.0,'apple']
print(list1)

[1, 4.0, 'apple']


In [7]:
import numpy as np
arr1=np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [9]:
import numpy as np 
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3.5,5])
print(arr1+arr2)

[2.  4.  6.5 9. ]


type conversion take place if stored different data types.

In [10]:
arr2=np.array([1,4.0,'Apple'])
print(arr2)

['1' '4.0' 'Apple']


In [21]:
arr2=np.array([2,2.5,'apple'])
arr2=np.array([5,6.8,'boy'])
print(arr2)

['5' '6.8' 'boy']


In [25]:
print(arr2)

['5' '6.8' 'boy']


In [29]:
import numpy as np
arr1=np.array([4,5.8,8])
arr2=np.array([7,9.8,5])
print(arr1+arr2)

[11.  15.6 13. ]


In [30]:
arr=np.array([5,10,15,20])
print(arr)
print(type(arr))

[ 5 10 15 20]
<class 'numpy.ndarray'>


In [31]:
arr/5

array([1., 2., 3., 4.])

In [32]:
list1=[5,10,15,20]
print(list1)

[5, 10, 15, 20]


creating a scalar array

In [50]:
s=np.array(5)
print(s)
print(np.ndim(s))
print(s.dtype)

5
0
int32


In [51]:
print(s.dtype)

int32


In [52]:
s=np.array([5,10,15,85,5.5])
print(s)

[ 5.  10.  15.  85.   5.5]


In [53]:
print(s.dtype)

float64


In [55]:
s=np.array([5,10,15,85,5.5,'python'])
print(s)
print(np.ndim(s))
print(s.dtype)

['5' '10' '15' '85' '5.5' 'python']
1
<U32


# creating dimensional array

In [58]:
a=[1,2,3,4]
A=np.array(a)
print(A)
print(A.dtype)
print(np.ndim(A))

[1 2 3 4]
int32
1


In [59]:
b=[[1,2,3],[4,5,6],[7,8,9]]
B=np.array(b)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
print(np.ndim(B))
print(B.dtype)

2
int32


In [64]:
C=[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]
C=np.array(c)
print(c)
print(np.ndim(C))
print(C.dtype)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
int32


In [66]:
print(A.ndim)
print(B.ndim)
print(C.ndim)

A.dtype
B.dtype
C.dtype

1
2
3


dtype('int32')

Accessing one dimensional array

In [69]:
a=[1,2,3,4,5]
A=np.array(a)
print(a)
print(A.shape)

[1, 2, 3, 4, 5]
(5,)


In [70]:
# method-1:positive indexing
print(a[3])

#method-2:negative indexing
print(a[-1])

4
5


In [71]:
print(a[0])
print(a[-3])

1
3


# Accesing two dim array

'i' respect to rows and 'j' respect to columns

In [72]:
# creating two dimensional array

b=[[1,2],[3,4]]
B=np.array(b)
print(B)
print(B.shape)

[[1 2]
 [3 4]]
(2, 2)


In [74]:
print(B[0][0])
print(B[-2][-2])

1
1


In [75]:
print(B[1][0])
print(B[-1][-2])

3
3


Accessing Three _Dimension Array

two dimension array within arrays is called three-dimension arrays.

"i"matrix index."j"is row and"k" is columns.

In [81]:
c=[[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]]
D=np.array(c)
print(D)
print(C.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)


accessing element 3

In [83]:
print(c[0][0][2])
print(c[-2][-3][-1])

3
3


accessing element 6 and 13

In [89]:
print(c[0][1][2])
print(c[-1][-2][-3])

6
13


accessing element 18

In [91]:
print(c[1][2][2])
print(c[-1][-1][-1])

18
18


Numpy array 

create sample numpy array

In [7]:
import numpy as np
a=np.arange(12)
new_a=a.reshape(2,6)
print(a)
print(type(a))
print(new_a)
print(new_a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
2


let's convert 2-d array to 1-d array

In [8]:
b=[[1,2,3],[4,5,6],[7,8,9]]
B=np.array(b)
print(B)
print(B.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [10]:
new_B=B.reshape(9)
print(new_B)
print(B.ndim)

[1 2 3 4 5 6 7 8 9]
2


In [11]:
b=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
B=np.array(b)
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
new_B=B.reshape(4,-1)
print(new_B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Slicing operation

one dim array

In [13]:
a=[1,4,7,11,6,3]
A=np.array(a)
print(A)
print(type(A))

[ 1  4  7 11  6  3]
<class 'numpy.ndarray'>


In [21]:
print(A[1:4:1])
print(A[-1:4:2])
print(A[-1:4:1])
print(A[1:-2:1])
print(A[2:5:2])
print(A[0:3:1])

[ 4  7 11]
[]
[]
[ 4  7 11]
[7 6]
[1 4 7]


In [24]:
print(A[:3])
print(A[2:])
print(A[::2])

[1 4 7]
[ 7 11  6  3]
[1 7 6]


In [25]:
print(A[::])

[ 1  4  7 11  6  3]


In [26]:
b=[[4,7,11],[6,13,9],[2,12,100]]
B=np.array(b)
print(B)
print(type(B))

[[  4   7  11]
 [  6  13   9]
 [  2  12 100]]
<class 'numpy.ndarray'>


General format

.array_name[rows_format,column_format]
rows_format and column format
=[start,end,step]
step is optional and default value is 1

In [27]:
print(B[1: 3: 1, 0: 2: 1]) #get sub matrix[6,13],[2,12] 

[[ 6 13]
 [ 2 12]]


In [28]:
print(B[1:3:1,2:3:1]) # starting index of rows is 1 and ending is 3 as 3 is exclusive.starting index of column is 2 and ending is 3

[[  9]
 [100]]


In [29]:
print(B[:,:])

[[  4   7  11]
 [  6  13   9]
 [  2  12 100]]


THREE DIMENSIONAL ARRAY

General format(i,j,k)

In [31]:
c=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
C=np.array(c)
print(C)
print(C.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [32]:
c=[[1,2,3],[10,11,12]]
C=np.array(c)
print(C)
print(C.shape)

[[ 1  2  3]
 [10 11 12]]
(2, 3)


In [36]:
c=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
C=np.array(c)
print(C)
print(C.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [38]:
C[:,:,:] 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
C[0:1,:,:]#slice only one matrix in the 3-D array

array([[[1, 2, 3],
        [4, 5, 6]]])

In [40]:
C[:,:,0:1] #the 0th column in all the matrices

array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]])

view vs. in numpy

1.changes made to the view will affect to the original array,whereas changes made to the copy will not affect original array.
2.view is just the view of original array and copy is like creating a new array.

# Understand the functionality of view()

note:view does not owns the data

In [41]:
arr1=np.array([10,20,30,40])
print(arr1)


[10 20 30 40]


In [42]:
arr=np.array([10,20,30,40])
print(arr)


[10 20 30 40]


In [44]:
arr2=arr1.view()
arr2[1]=1000
print(arr2)

[  10 1000   30   40]


In [45]:
arr2=arr1.view()
arr2[2]=2000
print(arr2)

[  10 1000 2000   40]


In [46]:
arr2=arr1.view()
arr2[-2]=4000
print(arr2)

[  10 1000 4000   40]


In [47]:
print(arr1)

[  10 1000 4000   40]


Let's understand the functionality of copy()

In [49]:
arr1=np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [52]:
arr2=arr1.copy()
arr2[1]=1000
print(arr2)
print(arr1)

[  10 1000   30   40]
[10 20 30 40]


# Hstack vs Vstack
1.Hstack is used to join two arrays Horizontally.
2.Vstack is used to join two arrays vertically.

In [54]:
# Hstack
a=np.array([1,2,3])
b=np.array([4,5,6])

print("a:{}".format(a))
print("Dimension of a:",a.ndim)

print("b:{}".format(b))
print("Dimension of b:",b.ndim)

a:[1 2 3]
Dimension of a: 1
b:[4 5 6]
Dimension of b: 1


In [56]:
c=np.hstack((a,b))
print("c:{}".format(c))
print("Dimension of c:",c.ndim)

c:[1 2 3 4 5 6]
Dimension of c: 1


In [57]:
#Vstack
a=np.array([1,2,3])
b=np.array([4,5,6])

print("a:{}".format(a))
print("Dimension of a:",a.ndim)

print("b:{}".format(b))
print("Dimension of b:",b.ndim)

a:[1 2 3]
Dimension of a: 1
b:[4 5 6]
Dimension of b: 1


In [58]:
c=np.hstack((a,b))
print("c:{}".format(c))
print("Dimension of c:",c.ndim)

c:[1 2 3 4 5 6]
Dimension of c: 1


# Numpy concatenation 

In [60]:
#Array A
import numpy as np
a=[[1,2],[4,5]]
A=np.array(a)
print(A)
print(A.shape)

[[1 2]
 [4 5]]
(2, 2)


In [61]:
# Array B
b=[[7],[8]]
B=np.array(b)
print(B)
print(B.shape)

[[7]
 [8]]
(2, 1)


In [85]:
# Array c
c=[[9,10]]
C=np.array(c)
print(C)
print(C.shape)

[[ 9 10]]
(1, 2)


# note:
1.when axis=0 both concatination arrays should have same number of columns[Think like adding a new row]
2.When axis=1,both concatinating arrays should have same number of rows[adding a new column]

In [86]:
# concatination Aand C

print(A.shape)
print(C.shape)

(2, 2)
(1, 2)


.Here we have same number of columns.

In [87]:
D=np.concatenate((A,C),axis=0)
print(D)
print(D.shape)

[[ 1  2]
 [ 4  5]
 [ 9 10]]
(3, 2)


# concatenate A and B

In [79]:
print(A.shape)

(2, 2)


In [80]:
print(B.shape)

(2, 1)


.Here we have same number of rows

In [81]:
E=np.concatenate((A,B),axis=1)
print(E)
print(E.shape)

[[1 2 7]
 [4 5 8]]
(2, 3)


# note:when you tried to add of different rows with axis=1,we will get error.
    
    Different Columns.

In [90]:
print(A.shape)
print(C.shape)     

(2, 2)
(1, 2)


In [94]:
F=np.concatenate((A,C),axis=1)
print(F)
print(F.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

while concatenate arrays of different columns

In [92]:
print(A.shape)
print(B.shape)    

(2, 2)
(2, 1)


In [93]:
G=np.concatenate((A,B),axis=0)
print(G)
print(G.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1